<template>
    <div class="container max-w-4xl mx-auto px-4 py-8"><div class="prose prose-invert"><h1 class="text-3xl font-bold mb-8">Refund and Fraud Policy</h1><h2 class="text-2xl font-semibold mt-8 mb-4">1. Overview</h2><p>At <a href="https://kutt.ai" class="c-primary">kutt.ai</a> ("the Application"), our commitment is to provide an unparalleled video generation experience. This document outlines our policies on fees, subscription renewals and cancellations, refunds, and measures to counteract fraudulent activities on our platform.</p><h2 class="text-2xl font-semibold mt-8 mb-4">2. Fees</h2><p>Services or parts thereof provided on a fee-based model require you to select a payment plan and submit information related to your credit card or other payment methods. You declare and guarantee to <a href="https://kutt.ai" class="c-primary">kutt.ai</a> that all such information is accurate, and you are authorized to use the specified payment method.</p><p>You are obligated to promptly update your account information with <a href="https://kutt.ai" class="c-primary">kutt.ai</a> or the designated payment processor to reflect any changes such as in your billing address or credit card expiration date. You agree to remit payments according to the terms of the selected payment plan and the terms of service of this Application.</p><p>Should your payment plan include an automatically renewing ongoing subscription, you hereby authorize <a href="https://kutt.ai" class="c-primary">kutt.ai</a> and its payment processors to bill your payment method periodically in advance in accordance with the terms of the applicable payment plan until such time as you terminate your account. Furthermore, you agree to settle any charges thus incurred.</p><p>Should you contest any charges, you are required to notify <a href="https://kutt.ai" class="c-primary">kutt.ai</a> within sixty (60) days from the charge date or within a longer period if mandated by applicable law.</p><p>Detailed information about our free and premium subscription products, including the pricing of subscriptions, is available at https://<a href="https://kutt.ai" class="c-primary">kutt.ai</a>/pricing.</p><p>We reserve the right to modify the prices on <a href="https://kutt.ai" class="c-primary">kutt.ai</a>. Should there be a price change, <a href="https://kutt.ai" class="c-primary">kutt.ai</a> will notify you at least fifteen (15) days prior to the effective date of the change via the service user interface, popup notification, email, or other reasonable methods as determined by <a href="https://kutt.ai" class="c-primary">kutt.ai</a>. Continuation of service use after the effective date of the price change constitutes your agreement to the revised charges.</p><p>You are responsible for all applicable taxes associated with the services, excluding taxes levied on the net income of <a href="https://kutt.ai" class="c-primary">kutt.ai</a>.</p><h2 class="text-2xl font-semibold mt-8 mb-4">3. Subscription Renewals and Cancellations</h2><p>You consent that if you have purchased a subscription, it will renew automatically at the frequency stated on the subscription page (or monthly if unspecified) at the prevailing rate at the time of renewal. Your payment method will automatically be charged the applicable fees and taxes for each new subscription period at the start of each.</p><p>To prevent future subscription fees, you must cancel your subscription at least seven (7) days prior to the subscription renewal date by navigating to the subscription management section on our website or by notifying us via email at <a href="mailto:contact@kutt.ai" class="c-primary">contact@kutt.ai</a></p><p>Following your cancellation, you will retain access to the paid services until the end of your current paid subscription period.</p><h2 class="text-2xl font-semibold mt-8 mb-4">4. Refunds and Cancellations</h2><p>Due to the nature of AI-powered video generation services and the associated infrastructure costs, we generally do not offer refunds for purchases or subscriptions. However, we provide a limited number of free messages to allow you to evaluate our service before making a purchase. We believe this free trial provides sufficient opportunity to assess whether our application meets your needs.</p><p>By continuing with a paid subscription after the trial period, you acknowledge and accept our no-refund policy.</p><p>In the event of a refund dispute, we will conduct a thorough investigation, reviewing all relevant transaction data. We will communicate with you to gather additional information regarding your claim. Based on the evidence, we will determine the appropriate resolution—whether to dispute an unwarranted refund request or initiate a refund in verified cases. If a claim is found to be fraudulent, you may be held liable for any associated refund costs.</p><h2 class="text-2xl font-semibold mt-8 mb-4">5. Fraud Prevention</h2><p>To uphold the integrity of our platform, we adopt a zero-tolerance policy towards fraudulent conduct. We implement diverse strategies to mitigate fraud risks, including:</p><ul class="list-disc pl-6 mb-4"><li>Identity verification at registration</li><li>Advanced encryption protocols</li><li>AI-powered fraud detection</li></ul><p>We retain the right to immediately suspend or terminate accounts implicated in fraudulent transactions or misuse. Such activities may also be reported to the appropriate authorities.</p><p>Users are obliged to furnish accurate information and utilize <a href="https://kutt.ai" class="c-primary">kutt.ai</a> in accordance with our Terms of Service and relevant laws. Any suspicious activity should be reported to <a href="mailto:contact@kutt.ai" class="c-primary">contact@kutt.ai</a></p><h2 class="text-2xl font-semibold mt-8 mb-4">6. Modifications</h2><p>We may periodically update this Refund and Fraud Policy. Any changes will be published on our website and will be effective immediately.</p><p>For additional inquiries, please reach out to our support team at <a href="mailto:contact@kutt.ai" class="c-primary">contact@kutt.ai</a></p><p>This policy complements any statutory rights available under consumer protection regulations.</p></div></div>
</template>
<style scoped>
    .container {
        --f-primary: var(--f-blue-1);
    --f-primary-2: var(--f-blue-2);
    --f-gray-1: #888a8d;
    --f-gray-2: #3a3a3a;
    --f-gray-3: #656b75;
    --f-gray-4-text: #bdbfc1;
    --f-black-2: #0e1116;
    --f-black-3: #13181e;
    --f-bg-modal: #242d3a;
    --f-divider: #3d5188;
    --f-primary-hover: var(--f-primary-style-7);
    --f-primary-active: var(--f-primary-style-8);
    --f-text: #fff;
    --f-bg-base: #050505;
    --f-text-secondary: #ffffffcc;
    --f-bg-container: #141414;
    --f-text-tertiary: #888a8d;
    --f-bg-elevated: #191919;
    --f-bg-mask: #000000c7;
    --f-text-quaternary: #ffffff73;
    --f-border: #243461;
    --f-secondary: var(--f-primary-style-5);
    --f-primary-style-1: #13181e;
    --f-primary-style-2: #0e1116;
    --f-primary-style-3: #ff346673;
    --f-primary-style-4: #ff3466a6;
    --f-primary-style-5: #00ffd1;
    --f-primary-style-6: #3ca2f6;
    --f-primary-style-7: #0047ff;
    --f-primary-style-8: #dd1244;
    --f-secondary-style-1: #fffbe6;
    --f-secondary-style-2: #fff5bf;
    --f-secondary-style-3: #ffed8c;
    --f-secondary-style-4: #ffe459;
    --f-secondary-style-5: #ffc700;
    --f-secondary-style-6: #ffa800;
    --f-secondary-style-7: #f09000;
    --f-secondary-style-8: #df7800;
    --f-blue-1: #3ca2f6;
    --f-blue-2: #0047ff;
    --f-blue-3: #1f86ff73;
    --f-blue-4: #1f86ffa6;
    --f-blue-5: #1f86ff;
    --f-blue-6: #0171f3;
    --f-blue-7: #086ce2;
    --f-green-1: #53ce161a;
    --f-green-2: #53ce1640;
    --f-green-3: #53ce1673;
    --f-green-4: #53ce16a6;
    --f-green-5: #55ce19;
    --f-green-6: #48c00d;
    --f-green-7: #3aaf00;
    --f-yellow-1: #ffc7001a;
    --f-yellow-2: #ffc70040;
    --f-yellow-3: #ffc70073;
    --f-yellow-4: #ffc700a6;
    --f-yellow-5: #ffc700;
    --f-yellow-6: #ffb700;
    --f-yellow-7: #efac00;
    --f-orange-1: #ff8d241a;
    --f-orange-2: #ff8d2440;
    --f-orange-3: #ff8d2473;
    --f-orange-4: #ff8d24a6;
    --f-orange-5: #ff8d24;
    --f-orange-6: #ff7d05;
    --f-orange-7: #ee7403;
    --f-red-1: #ff4f511a;
    --f-red-2: #ff4f5140;
    --f-red-3: #ff4f5173;
    --f-red-4: #ff4f51a6;
    --f-red-5: #ff4f51;
    --f-red-6: #f5222d;
    --f-red-7: #cf1322;
    --f-secondary-hover: var(--f-secondary-style-6);
    --f-secondary-active: var(--f-secondary-style-7);
    --f-bg-layout: #1d1d1d;
    --f-text-disabled: #ffffff59;
    --f-bg-hover: #212121;
    --f-text-invert: #000;
    --f-bg-active: #242424;
    --f-bg-disabled: #3e3e3e80;
    --f-success-bg: var(--f-green-1);
    --f-success-bg-hover: var(--f-green-2);
    --f-success-border: var(--f-green-3);
    --f-success-border-hover: var(--f-green-4);
    --f-success: var(--f-green-5);
    --f-success-hover: var(--f-green-6);
    --f-success-active: var(--f-green-7);
    --f-warning-bg: var(--f-yellow-1);
    --f-warning-bg-hover: var(--f-yellow-2);
    --f-warning-border: var(--f-yellow-3);
    --f-warning-border-hover: var(--f-yellow-4);
    --f-warning: var(--f-yellow-5);
    --f-warning-hover: var(--f-yellow-6);
    --f-warning-active: var(--f-yellow-7);
    --f-error-bg: var(--f-red-1);
    --f-other-1: #0a0a0a;
    --f-other-2: #0000004d;
    --f-other-3: #14141499;
    --f-other-4: #ffffff1a;
    --f-other-5: #fff;
    --f-other-6: #fff;
    --f-other-7: #fff;
    --f-other-8: #fff;
    --f-other-9: #fff;
    --f-other-10: #fff;
    --f-error-bg-hover: var(--f-red-2);
    --f-error-border: var(--f-red-3);
    --f-error-border-hover: var(--f-red-4);
    --f-error: var(--f-red-5);
    --f-error-hover: var(--f-red-6);
    --f-border-hover: #dcdcdcd9;
    --f-border-active: #dcdcdca6;
    --f-text-invert-secondary: #000000bf;
    --f-border-secondary: #232323;
    --f-error-active: var(--f-red-7);
    --f-sub: #00ffd1;
    color-scheme: var(--mantine-color-scheme);
    --mantine-z-index-app: 100;
    --mantine-z-index-modal: 200;
    --mantine-z-index-popover: 300;
    --mantine-z-index-overlay: 400;
    --mantine-z-index-max: 9999;
    --mantine-scale: 1;
    --mantine-cursor-type: default;
    --mantine-webkit-font-smoothing: antialiased;
    --mantine-moz-font-smoothing: grayscale;
    --mantine-color-white: #fff;
    --mantine-color-black: #000;
    --mantine-line-height: 1.55;
    --mantine-font-family-monospace: ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace;
    --mantine-heading-font-weight: 700;
    --mantine-radius-default: calc(0.25rem * var(--mantine-scale));
    --mantine-breakpoint-xs: 36em;
    --mantine-breakpoint-sm: 48em;
    --mantine-breakpoint-md: 62em;
    --mantine-breakpoint-lg: 75em;
    --mantine-breakpoint-xl: 88em;
    --mantine-spacing-xs: calc(0.625rem * var(--mantine-scale));
    --mantine-spacing-sm: calc(0.75rem * var(--mantine-scale));
    --mantine-spacing-md: calc(1rem * var(--mantine-scale));
    --mantine-spacing-lg: calc(1.25rem * var(--mantine-scale));
    --mantine-spacing-xl: calc(2rem * var(--mantine-scale));
    --mantine-font-size-xs: calc(0.75rem * var(--mantine-scale));
    --mantine-font-size-sm: calc(0.875rem * var(--mantine-scale));
    --mantine-font-size-md: calc(1rem * var(--mantine-scale));
    --mantine-font-size-lg: calc(1.125rem * var(--mantine-scale));
    --mantine-font-size-xl: calc(1.25rem * var(--mantine-scale));
    --mantine-line-height-xs: 1.4;
    --mantine-line-height-sm: 1.45;
    --mantine-line-height-md: 1.55;
    --mantine-line-height-lg: 1.6;
    --mantine-line-height-xl: 1.65;
    --mantine-shadow-xs: 0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0,0,0,.05),0 calc(0.0625rem * var(--mantine-scale)) calc(0.125rem * var(--mantine-scale)) rgba(0,0,0,.1);
    --mantine-shadow-sm: 0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0,0,0,.05),rgba(0,0,0,.05) 0 calc(0.625rem * var(--mantine-scale)) calc(0.9375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)),rgba(0,0,0,.04) 0 calc(0.4375rem * var(--mantine-scale)) calc(0.4375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale));
    --mantine-shadow-md: 0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0,0,0,.05),rgba(0,0,0,.05) 0 calc(1.25rem * var(--mantine-scale)) calc(1.5625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)),rgba(0,0,0,.04) 0 calc(0.625rem * var(--mantine-scale)) calc(0.625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale));
    --mantine-shadow-lg: 0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0,0,0,.05),rgba(0,0,0,.05) 0 calc(1.75rem * var(--mantine-scale)) calc(1.4375rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)),rgba(0,0,0,.04) 0 calc(0.75rem * var(--mantine-scale)) calc(0.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale));
    --mantine-shadow-xl: 0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0,0,0,.05),rgba(0,0,0,.05) 0 calc(2.25rem * var(--mantine-scale)) calc(1.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)),rgba(0,0,0,.04) 0 calc(1.0625rem * var(--mantine-scale)) calc(1.0625rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale));
    --mantine-radius-xs: calc(0.125rem * var(--mantine-scale));
    --mantine-radius-sm: calc(0.25rem * var(--mantine-scale));
    --mantine-radius-md: calc(0.5rem * var(--mantine-scale));
    --mantine-radius-lg: calc(1rem * var(--mantine-scale));
    --mantine-radius-xl: calc(2rem * var(--mantine-scale));
    --mantine-color-dark-0: #c9c9c9;
    --mantine-color-dark-1: #b8b8b8;
    --mantine-color-dark-2: #828282;
    --mantine-color-dark-3: #696969;
    --mantine-color-dark-4: #424242;
    --mantine-color-dark-5: #3b3b3b;
    --mantine-color-dark-6: #2e2e2e;
    --mantine-color-dark-7: #242424;
    --mantine-color-dark-8: #1f1f1f;
    --mantine-color-dark-9: #141414;
    --mantine-color-gray-0: #f8f9fa;
    --mantine-color-gray-1: #f1f3f5;
    --mantine-color-gray-2: #e9ecef;
    --mantine-color-gray-3: #dee2e6;
    --mantine-color-gray-4: #ced4da;
    --mantine-color-gray-5: #adb5bd;
    --mantine-color-gray-6: #868e96;
    --mantine-color-gray-7: #495057;
    --mantine-color-gray-8: #343a40;
    --mantine-color-gray-9: #212529;
    --mantine-color-red-0: #fff5f5;
    --mantine-color-red-1: #ffe3e3;
    --mantine-color-red-2: #ffc9c9;
    --mantine-color-red-3: #ffa8a8;
    --mantine-color-red-4: #ff8787;
    --mantine-color-red-5: #ff6b6b;
    --mantine-color-red-6: #fa5252;
    --mantine-color-red-7: #f03e3e;
    --mantine-color-red-8: #e03131;
    --mantine-color-red-9: #c92a2a;
    --mantine-color-pink-0: #fff0f6;
    --mantine-color-pink-1: #ffdeeb;
    --mantine-color-pink-2: #fcc2d7;
    --mantine-color-pink-3: #faa2c1;
    --mantine-color-pink-4: #f783ac;
    --mantine-color-pink-5: #f06595;
    --mantine-color-pink-6: #e64980;
    --mantine-color-pink-7: #d6336c;
    --mantine-color-pink-8: #c2255c;
    --mantine-color-pink-9: #a61e4d;
    --mantine-color-grape-0: #f8f0fc;
    --mantine-color-grape-1: #f3d9fa;
    --mantine-color-grape-2: #eebefa;
    --mantine-color-grape-3: #e599f7;
    --mantine-color-grape-4: #da77f2;
    --mantine-color-grape-5: #cc5de8;
    --mantine-color-grape-6: #be4bdb;
    --mantine-color-grape-7: #ae3ec9;
    --mantine-color-grape-8: #9c36b5;
    --mantine-color-grape-9: #862e9c;
    --mantine-color-violet-0: #f3f0ff;
    --mantine-color-violet-1: #e5dbff;
    --mantine-color-violet-2: #d0bfff;
    --mantine-color-violet-3: #b197fc;
    --mantine-color-violet-4: #9775fa;
    --mantine-color-violet-5: #845ef7;
    --mantine-color-violet-6: #7950f2;
    --mantine-color-violet-7: #7048e8;
    --mantine-color-violet-8: #6741d9;
    --mantine-color-violet-9: #5f3dc4;
    --mantine-color-indigo-0: #edf2ff;
    --mantine-color-indigo-1: #dbe4ff;
    --mantine-color-indigo-2: #bac8ff;
    --mantine-color-indigo-3: #91a7ff;
    --mantine-color-indigo-4: #748ffc;
    --mantine-color-indigo-5: #5c7cfa;
    --mantine-color-indigo-6: #4c6ef5;
    --mantine-color-indigo-7: #4263eb;
    --mantine-color-indigo-8: #3b5bdb;
    --mantine-color-indigo-9: #364fc7;
    --mantine-color-blue-0: #e7f5ff;
    --mantine-color-blue-1: #d0ebff;
    --mantine-color-blue-2: #a5d8ff;
    --mantine-color-blue-3: #74c0fc;
    --mantine-color-blue-4: #4dabf7;
    --mantine-color-blue-5: #339af0;
    --mantine-color-blue-6: #228be6;
    --mantine-color-blue-7: #1c7ed6;
    --mantine-color-blue-8: #1971c2;
    --mantine-color-blue-9: #1864ab;
    --mantine-color-cyan-0: #e3fafc;
    --mantine-color-cyan-1: #c5f6fa;
    --mantine-color-cyan-2: #99e9f2;
    --mantine-color-cyan-3: #66d9e8;
    --mantine-color-cyan-4: #3bc9db;
    --mantine-color-cyan-5: #22b8cf;
    --mantine-color-cyan-6: #15aabf;
    --mantine-color-cyan-7: #1098ad;
    --mantine-color-cyan-8: #0c8599;
    --mantine-color-cyan-9: #0b7285;
    --mantine-color-teal-0: #e6fcf5;
    --mantine-color-teal-1: #c3fae8;
    --mantine-color-teal-2: #96f2d7;
    --mantine-color-teal-3: #63e6be;
    --mantine-color-teal-4: #38d9a9;
    --mantine-color-teal-5: #20c997;
    --mantine-color-teal-6: #12b886;
    --mantine-color-teal-7: #0ca678;
    --mantine-color-teal-8: #099268;
    --mantine-color-teal-9: #087f5b;
    --mantine-color-green-0: #ebfbee;
    --mantine-color-green-1: #d3f9d8;
    --mantine-color-green-2: #b2f2bb;
    --mantine-color-green-3: #8ce99a;
    --mantine-color-green-4: #69db7c;
    --mantine-color-green-5: #51cf66;
    --mantine-color-green-6: #40c057;
    --mantine-color-green-7: #37b24d;
    --mantine-color-green-8: #2f9e44;
    --mantine-color-green-9: #2b8a3e;
    --mantine-color-lime-0: #f4fce3;
    --mantine-color-lime-1: #e9fac8;
    --mantine-color-lime-2: #d8f5a2;
    --mantine-color-lime-3: #c0eb75;
    --mantine-color-lime-4: #a9e34b;
    --mantine-color-lime-5: #94d82d;
    --mantine-color-lime-6: #82c91e;
    --mantine-color-lime-7: #74b816;
    --mantine-color-lime-8: #66a80f;
    --mantine-color-lime-9: #5c940d;
    --mantine-color-yellow-0: #fff9db;
    --mantine-color-yellow-1: #fff3bf;
    --mantine-color-yellow-2: #ffec99;
    --mantine-color-yellow-3: #ffe066;
    --mantine-color-yellow-4: #ffd43b;
    --mantine-color-yellow-5: #fcc419;
    --mantine-color-yellow-6: #fab005;
    --mantine-color-yellow-7: #f59f00;
    --mantine-color-yellow-8: #f08c00;
    --mantine-color-yellow-9: #e67700;
    --mantine-color-orange-0: #fff4e6;
    --mantine-color-orange-1: #ffe8cc;
    --mantine-color-orange-2: #ffd8a8;
    --mantine-color-orange-3: #ffc078;
    --mantine-color-orange-4: #ffa94d;
    --mantine-color-orange-5: #ff922b;
    --mantine-color-orange-6: #fd7e14;
    --mantine-color-orange-7: #f76707;
    --mantine-color-orange-8: #e8590c;
    --mantine-color-orange-9: #d9480f;
    --mantine-h1-font-size: calc(2.125rem * var(--mantine-scale));
    --mantine-h1-line-height: 1.3;
    --mantine-h1-font-weight: 700;
    --mantine-h2-font-size: calc(1.625rem * var(--mantine-scale));
    --mantine-h2-line-height: 1.35;
    --mantine-h2-font-weight: 700;
    --mantine-h3-font-size: calc(1.375rem * var(--mantine-scale));
    --mantine-h3-line-height: 1.4;
    --mantine-h3-font-weight: 700;
    --mantine-h4-font-size: calc(1.125rem * var(--mantine-scale));
    --mantine-h4-line-height: 1.45;
    --mantine-h4-font-weight: 700;
    --mantine-h5-font-size: calc(1rem * var(--mantine-scale));
    --mantine-h5-line-height: 1.5;
    --mantine-h5-font-weight: 700;
    --mantine-h6-font-size: calc(0.875rem * var(--mantine-scale));
    --mantine-h6-line-height: 1.5;
    --mantine-h6-font-weight: 700;
    --mantine-font-family: '__GeistSans_fb8f2c', '__GeistSans_Fallback_fb8f2c';
    --mantine-font-family-headings: '__GeistSans_fb8f2c', '__GeistSans_Fallback_fb8f2c';
    --mantine-primary-color-filled: var(--mantine-color-custom-filled);
    --mantine-primary-color-filled-hover: var(--mantine-color-custom-filled-hover);
    --mantine-primary-color-light: var(--mantine-color-custom-light);
    --mantine-primary-color-light-hover: var(--mantine-color-custom-light-hover);
    --mantine-primary-color-light-color: var(--mantine-color-custom-light-color);
    --mantine-primary-color-0: var(--mantine-color-custom-0);
    --mantine-primary-color-1: var(--mantine-color-custom-1);
    --mantine-primary-color-2: var(--mantine-color-custom-2);
    --mantine-primary-color-3: var(--mantine-color-custom-3);
    --mantine-primary-color-4: var(--mantine-color-custom-4);
    --mantine-primary-color-5: var(--mantine-color-custom-5);
    --mantine-primary-color-6: var(--mantine-color-custom-6);
    --mantine-primary-color-7: var(--mantine-color-custom-7);
    --mantine-primary-color-8: var(--mantine-color-custom-8);
    --mantine-primary-color-9: var(--mantine-color-custom-9);
    --mantine-color-custom-0: #3CA2F6;
    --mantine-color-custom-1: #3CA2F6;
    --mantine-color-custom-2: #3CA2F6;
    --mantine-color-custom-3: #3CA2F6;
    --mantine-color-custom-4: #3CA2F6;
    --mantine-color-custom-5: #3CA2F6;
    --mantine-color-custom-6: #3CA2F6;
    --mantine-color-custom-7: #3CA2F6;
    --mantine-color-custom-8: #3CA2F6;
    --mantine-color-custom-9: #3CA2F6;
    --app-shell-header-height: calc(3rem * var(--mantine-scale));
    --app-shell-header-offset: calc(3rem * var(--mantine-scale));
    --app-shell-padding: 0px;
    --mantine-color-scheme: dark;
    --mantine-primary-color-contrast: var(--mantine-color-white);
    --mantine-color-bright: var(--mantine-color-white);
    --mantine-color-text: var(--mantine-color-dark-0);
    --mantine-color-body: var(--mantine-color-dark-7);
    --mantine-color-error: var(--mantine-color-red-8);
    --mantine-color-placeholder: var(--mantine-color-dark-3);
    --mantine-color-default: var(--mantine-color-dark-6);
    --mantine-color-default-hover: var(--mantine-color-dark-5);
    --mantine-color-default-color: var(--mantine-color-white);
    --mantine-color-default-border: var(--mantine-color-dark-4);
    --mantine-color-dimmed: var(--mantine-color-dark-2);
    --mantine-color-dark-text: var(--mantine-color-dark-4);
    --mantine-color-dark-filled: var(--mantine-color-dark-8);
    --mantine-color-dark-filled-hover: var(--mantine-color-dark-7);
    --mantine-color-dark-light: rgba(36,36,36,.15);
    --mantine-color-dark-light-hover: rgba(36,36,36,.2);
    --mantine-color-dark-light-color: var(--mantine-color-dark-3);
    --mantine-color-dark-outline: var(--mantine-color-dark-4);
    --mantine-color-dark-outline-hover: rgba(36,36,36,.05);
    --mantine-color-gray-text: var(--mantine-color-gray-4);
    --mantine-color-gray-filled: var(--mantine-color-gray-8);
    --mantine-color-gray-filled-hover: var(--mantine-color-gray-9);
    --mantine-color-gray-light: hsla(210,7%,56%,.15);
    --mantine-color-gray-light-hover: hsla(210,7%,56%,.2);
    --mantine-color-gray-light-color: var(--mantine-color-gray-3);
    --mantine-color-gray-outline: var(--mantine-color-gray-4);
    --mantine-color-gray-outline-hover: rgba(206,212,218,.05);
    --mantine-color-red-text: var(--mantine-color-red-4);
    --mantine-color-red-filled: var(--mantine-color-red-8);
    --mantine-color-red-filled-hover: var(--mantine-color-red-9);
    --mantine-color-red-light: rgba(250,82,82,.15);
    --mantine-color-red-light-hover: rgba(250,82,82,.2);
    --mantine-color-red-light-color: var(--mantine-color-red-3);
    --mantine-color-red-outline: var(--mantine-color-red-4);
    --mantine-color-red-outline-hover: hsla(0,100%,76%,.05);
    --mantine-color-pink-text: var(--mantine-color-pink-4);
    --mantine-color-pink-filled: var(--mantine-color-pink-8);
    --mantine-color-pink-filled-hover: var(--mantine-color-pink-9);
    --mantine-color-pink-light: rgba(230,73,128,.15);
    --mantine-color-pink-light-hover: rgba(230,73,128,.2);
    --mantine-color-pink-light-color: var(--mantine-color-pink-3);
    --mantine-color-pink-outline: var(--mantine-color-pink-4);
    --mantine-color-pink-outline-hover: rgba(247,131,172,.05);
    --mantine-color-grape-text: var(--mantine-color-grape-4);
    --mantine-color-grape-filled: var(--mantine-color-grape-8);
    --mantine-color-grape-filled-hover: var(--mantine-color-grape-9);
    --mantine-color-grape-light: rgba(190,75,219,.15);
    --mantine-color-grape-light-hover: rgba(190,75,219,.2);
    --mantine-color-grape-light-color: var(--mantine-color-grape-3);
    --mantine-color-grape-outline: var(--mantine-color-grape-4);
    --mantine-color-grape-outline-hover: rgba(218,119,242,.05);
    --mantine-color-violet-text: var(--mantine-color-violet-4);
    --mantine-color-violet-filled: var(--mantine-color-violet-8);
    --mantine-color-violet-filled-hover: var(--mantine-color-violet-9);
    --mantine-color-violet-light: rgba(121,80,242,.15);
    --mantine-color-violet-light-hover: rgba(121,80,242,.2);
    --mantine-color-violet-light-color: var(--mantine-color-violet-3);
    --mantine-color-violet-outline: var(--mantine-color-violet-4);
    --mantine-color-violet-outline-hover: rgba(151,117,250,.05);
    --mantine-color-indigo-text: var(--mantine-color-indigo-4);
    --mantine-color-indigo-filled: var(--mantine-color-indigo-8);
    --mantine-color-indigo-filled-hover: var(--mantine-color-indigo-9);
    --mantine-color-indigo-light: rgba(76,110,245,.15);
    --mantine-color-indigo-light-hover: rgba(76,110,245,.2);
    --mantine-color-indigo-light-color: var(--mantine-color-indigo-3);
    --mantine-color-indigo-outline: var(--mantine-color-indigo-4);
    --mantine-color-indigo-outline-hover: rgba(116,143,252,.05);
    --mantine-color-blue-text: var(--mantine-color-blue-4);
    --mantine-color-blue-filled: var(--mantine-color-blue-8);
    --mantine-color-blue-filled-hover: var(--mantine-color-blue-9);
    --mantine-color-blue-light: rgba(34,139,230,.15);
    --mantine-color-blue-light-hover: rgba(34,139,230,.2);
    --mantine-color-blue-light-color: var(--mantine-color-blue-3);
    --mantine-color-blue-outline: var(--mantine-color-blue-4);
    --mantine-color-blue-outline-hover: rgba(77,171,247,.05);
    --mantine-color-cyan-text: var(--mantine-color-cyan-4);
    --mantine-color-cyan-filled: var(--mantine-color-cyan-8);
    --mantine-color-cyan-filled-hover: var(--mantine-color-cyan-9);
    --mantine-color-cyan-light: rgba(21,170,191,.15);
    --mantine-color-cyan-light-hover: rgba(21,170,191,.2);
    --mantine-color-cyan-light-color: var(--mantine-color-cyan-3);
    --mantine-color-cyan-outline: var(--mantine-color-cyan-4);
    --mantine-color-cyan-outline-hover: rgba(59,201,219,.05);
    --mantine-color-teal-text: var(--mantine-color-teal-4);
    --mantine-color-teal-filled: var(--mantine-color-teal-8);
    --mantine-color-teal-filled-hover: var(--mantine-color-teal-9);
    --mantine-color-teal-light: rgba(18,184,134,.15);
    --mantine-color-teal-light-hover: rgba(18,184,134,.2);
    --mantine-color-teal-light-color: var(--mantine-color-teal-3);
    --mantine-color-teal-outline: var(--mantine-color-teal-4);
    --mantine-color-teal-outline-hover: rgba(56,217,169,.05);
    --mantine-color-green-text: var(--mantine-color-green-4);
    --mantine-color-green-filled: var(--mantine-color-green-8);
    --mantine-color-green-filled-hover: var(--mantine-color-green-9);
    --mantine-color-green-light: rgba(64,192,87,.15);
    --mantine-color-green-light-hover: rgba(64,192,87,.2);
    --mantine-color-green-light-color: var(--mantine-color-green-3);
    --mantine-color-green-outline: var(--mantine-color-green-4);
    --mantine-color-green-outline-hover: rgba(105,219,124,.05);
    --mantine-color-lime-text: var(--mantine-color-lime-4);
    --mantine-color-lime-filled: var(--mantine-color-lime-8);
    --mantine-color-lime-filled-hover: var(--mantine-color-lime-9);
    --mantine-color-lime-light: rgba(130,201,30,.15);
    --mantine-color-lime-light-hover: rgba(130,201,30,.2);
    --mantine-color-lime-light-color: var(--mantine-color-lime-3);
    --mantine-color-lime-outline: var(--mantine-color-lime-4);
    --mantine-color-lime-outline-hover: rgba(169,227,75,.05);
    --mantine-color-yellow-text: var(--mantine-color-yellow-4);
    --mantine-color-yellow-filled: var(--mantine-color-yellow-8);
    --mantine-color-yellow-filled-hover: var(--mantine-color-yellow-9);
    --mantine-color-yellow-light: rgba(250,176,5,.15);
    --mantine-color-yellow-light-hover: rgba(250,176,5,.2);
    --mantine-color-yellow-light-color: var(--mantine-color-yellow-3);
    --mantine-color-yellow-outline: var(--mantine-color-yellow-4);
    --mantine-color-yellow-outline-hover: rgba(255,212,59,.05);
    --mantine-color-orange-text: var(--mantine-color-orange-4);
    --mantine-color-orange-filled: var(--mantine-color-orange-8);
    --mantine-color-orange-filled-hover: var(--mantine-color-orange-9);
    --mantine-color-orange-light: rgba(253,126,20,.15);
    --mantine-color-orange-light-hover: rgba(253,126,20,.2);
    --mantine-color-orange-light-color: var(--mantine-color-orange-3);
    --mantine-color-orange-outline: var(--mantine-color-orange-4);
    --mantine-color-orange-outline-hover: rgba(255,169,77,.05);
    --mantine-color-anchor: var(--mantine-color-custom-4);
    --mantine-color-custom-text: var(--mantine-color-custom-4);
    --mantine-color-custom-filled: var(--mantine-color-custom-8);
    --mantine-color-custom-filled-hover: var(--mantine-color-custom-9);
    --mantine-color-custom-light: rgba(60, 162, 246, 0.15);
    --mantine-color-custom-light-hover: rgba(60, 162, 246, 0.2);
    --mantine-color-custom-light-color: var(--mantine-color-custom-3);
    --mantine-color-custom-outline: var(--mantine-color-custom-4);
    --mantine-color-custom-outline-hover: rgba(60, 162, 246, 0.05);
    --innerHeight: 919px;
    --1vh: 9.19px;
    font-size: var(--mantine-font-size-md);
    line-height: var(--mantine-line-height);
    -webkit-font-smoothing: var(--mantine-webkit-font-smoothing);
    --font-racing-sans-one: "__Racing_Sans_One_97fb25","__Racing_Sans_One_Fallback_97fb25";
    font-family: __GeistSans_fb8f2c,__GeistSans_Fallback_fb8f2c;
    --font-geist-sans: "__GeistSans_fb8f2c","__GeistSans_Fallback_fb8f2c";
    --un-text-opacity: 1;
    --app-shell-border-color: var(--mantine-color-dark-4);
    --app-shell-transition-duration: 200ms;
    --app-shell-transition-timing-function: ease;
    box-sizing: border-box;
    margin-left: auto;
    margin-right: auto;
    max-width: 56rem;
    padding-left: 1rem;
    padding-right: 1rem;
    padding-top: 2rem;
    padding-bottom: 2rem;
    }
    html .max-w-\[900px\] {
    max-width: 900px;
}
html .md\:mb-16 {
    margin-bottom: 4rem;
}
html .h-1, html .h1 {
    height: .25rem;
}
html .\[\&_h1\]\:w-full h1, html .w-100\%, html .w-full {
    width: 100%;
}
html .my-8 {
    margin-top: 2rem;
    margin-bottom: 2rem;
}
html .\[background-image\:linear-gradient\(to_right\,rgb\(123\,244\,226\)\,rgb\(58\,109\,242\)\,rgb\(220\,255\,99\)\,rgb\(255\,190\,38\)\,rgb\(255\,92\,46\)\)\] {
    background-image: linear-gradient(90deg,#7bf4e2,#3a6df2,#dcff63,#ffbe26,#ff5c2e);
}
html .\[\&_ul\]\:mx-auto ul, html .mx-auto {
    margin-left: auto;
    margin-right: auto;
}
html .py-12 {
    padding-top: 3rem;
    padding-bottom: 3rem;
}
html .\[\&_h2\]\:md\:text-2xl h2, html .md\:text-2xl {
    font-size: 1.5rem;
    line-height: 2rem;
}
html .\[\&\[data-active\]\]\:font-semibold[data-active], html .\[\&_h2\]\:font-semibold h2, html .\[\&_h3\]\:font-semibold h3, html .\[\&_h4\]\:font-semibold h4, html .\[\&_span\]\:font-semibold span, html .font-600, html .font-semibold {
    font-weight: 600;
}
html .\[\&_h2\]\:mt-8 h2, html .mt-8 {
    margin-top: 2rem;
}
html .\[\&_h2\]\:mb-3 h2, html .mb-3 {
    margin-bottom: .75rem;
}
html .\[\&_h3\]\:md\:text-lg h3, html .md\:text-lg {
    font-size: 1.125rem;
    line-height: 1.75rem;
}
html .\[\&\[data-active\]\]\:font-semibold[data-active], html .\[\&_h2\]\:font-semibold h2, html .\[\&_h3\]\:font-semibold h3, html .\[\&_h4\]\:font-semibold h4, html .\[\&_span\]\:font-semibold span, html .font-600, html .font-semibold {
    font-weight: 600;
}
html .\[\&_h3\]\:my-3 h3, html .\[\&_h4\]\:my-3 h4, html .\[\&_strong\]\:my-3 strong, html .my-3 {
    margin-top: .75rem;
    margin-bottom: .75rem;
}
html .\[\&_li\]\:md\:text-sm li, html .\[\&_p\]\:md\:text-sm p {
    font-size: .875rem;
    line-height: 1.25rem;
}
html .\[\&_li\]\:mb-2 li, html .\[\&_p\]\:mb-2 p, html .mb-2 {
    margin-bottom: .5rem;
}
html .\[\&_h4\]\:text-sm h4, html .\[\&_ol\]\:text-sm ol, html .\[\&_p\]\:text-sm p, html .\[\&_ul\]\:text-sm ul, html .text-sm {
    font-size: .875rem;
    line-height: 1.25rem;
}
html .\[\&_ol\]\:ps-5 ol, html .\[\&_ul\]\:ps-5 ul {
    -webkit-padding-start: 1.25rem;
    padding-inline-start: 1.25rem;
}
html .\[\&_ul\]\:list-disc ul, html .list-disc {
    list-style-type: disc;
}
</style>